spring:
  datasource:
    url: jdbc:mysql://yourprotein.cy3ppn5iqua0.ap-northeast-2.rds.amazonaws.com:3306/yourprotein
    username: admin
    password: yourprotein!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8000
#  ssl:
#    enabled: true
#    enabled-protocols:
#      - TLSv1.1
#      - TLSv1.2
#    key-store: "/app/static/yourprotein_api.p12"
#    key-store-password: "yourprotein!"
#    key-store-type: "PKCS12"
kakao:
  client_id: 3d93f617a4d6fc388877925283f37797


